### ISSUE TITLE
bowtie2 mapping

### ISSUE THREAD

**Issue by zhangpicb** [mpmeers/JanssensEtAl_MPAL#1]
Hello @mpmeers @derekjanssensphd 

Thanks for your beautiful work!

I have a question about bowtie2 mapping.

```Bowtie2 version 2.3.4.3 to UCSC hg19 with the following options: --end-to-end --very-sensitive --no-mixed --no-discordant -q --phred33 -I 10 -X 700```

How to decide the parameters in ```-I 10 -X700```?

Thanks in advanced.

**Comment by mpmeers** [comment]
Hi,

The minimum fragment insert -I and maximum fragment insert -X are set based on a reasonable expectation of the fragment footprint generated in CUT&RUN/Tag experiments. At the low end, setting a cutoff of 10 omits extremely short fragments that may represent artifactual amplification biases with minimal loss of "real" biological signal (especially for histone modifications where the protected fragment is expected to be ~120-180 bp). At the high end, 700 allows for polynucleosomal fragments while removing artifactual long-range intra- or inter-chromosome mapping. Hope that helps.

Mike

**Comment by zhangpicb** [comment]
Hi @mpmeers ,

Thank you very much for your reply! 
I don't know if these parameters(```-I 10 -X700```) need to be changed when the data are paired-end 2 X 150bp. Because I find CUT&Tag data in the paper are paired-end 2 X 25bp.
Actually,I have a mouse TF Cut&Tag data,and the data are paired-end 2 X 150bp.

Thanks in advanced.

**Comment by mpmeers** [comment]
Hi,

We typically don't deal with such long reads so I can't say from experience whether any changes would be necessary in your case. However, since -I and -X are specifying "outer distance" between the outer termini of the reads that would not change based on your read length, I anticipate that the same parameters can be used for your 2x150. More details can be found in the [bowtie2 documentation](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml). In this work we sequenced everything to 2x25, so this shouldn't be an issue for these data in any case.

Mike

**Comment by mpmeers** [comment]
Closing since I think the question relating to specific data analysis from the paper has been answered.

Mike
